//! The Link Key (`CONTEXT.md`): 256 random bits from the RP2350's TRNG,
//! generated when the device is Claimed and persisted in `settings.rs`.
//! `main.rs` loads it at boot; `bt.rs` calls [`LinkKeys::generate`] from the
//! Pairing that Claims the device; `KEY` reads it through [`CurrentLinkKey`].
//! A Factory Reset erases it along with the rest of the settings region.
//!
//! Stored in plaintext; see `docs/adr/0007-plaintext-link-key.md`. Never log
//! it.

use core::cell::Cell;

use defmt::{info, warn};
use embassy_rp::peripherals::TRNG;
use embassy_rp::trng::Trng;
use embassy_sync::blocking_mutex::Mutex as BlockingMutex;
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::mutex::Mutex;
use pico_w_display::protocol::{LINK_KEY_LEN, LinkKeySource};

use crate::settings::SettingsStore;

/// The Link Key in force, once loaded at boot or generated by a Claim;
/// `None` while Unclaimed.
static LINK_KEY: BlockingMutex<CriticalSectionRawMutex, Cell<Option<[u8; LINK_KEY_LEN]>>> =
    BlockingMutex::new(Cell::new(None));

/// Puts `key` in force, e.g. the one `main.rs` loaded at boot.
pub fn publish(key: [u8; LINK_KEY_LEN]) {
    LINK_KEY.lock(|current| current.set(Some(key)));
}

/// Implements [`LinkKeySource`] for `KEY`.
pub struct CurrentLinkKey;

impl LinkKeySource for CurrentLinkKey {
    fn link_key(&self) -> Option<[u8; LINK_KEY_LEN]> {
        LINK_KEY.lock(Cell::get)
    }
}

/// Makes new Link Keys: owns the TRNG, and shares the settings store.
pub struct LinkKeys<'a> {
    pub trng: Trng<'static, TRNG>,
    pub settings: &'a Mutex<CriticalSectionRawMutex, SettingsStore>,
}

impl LinkKeys<'_> {
    /// Generates a fresh Link Key, persists it and puts it in force. A
    /// failed flash write is logged and the key is still put in force, so
    /// this Session's `KEY` works; the next boot then finds a Claimed device
    /// with no Link Key and generates another, which the app has to fetch
    /// again.
    pub async fn generate(&mut self) {
        let mut key = [0u8; LINK_KEY_LEN];
        self.trng.fill_bytes(&mut key).await;
        if self.settings.lock().await.save_link_key(&key).await.is_err() {
            warn!("link key not persisted");
        }
        publish(key);
        info!("link key generated");
    }
}
