/// Generates `lib/tz/posix_table.g.dart`, the IANA zone → POSIX TZ Rule
/// table the app sends `TZ` from, plus the firmware's
/// `pico_w_display/testdata/tz_rules.txt` fixture (every distinct rule, which
/// `tz.rs`'s tests check the device accepts).
///
/// Downloads the pinned IANA tzdata release, compiles it with the system
/// `zic`, and takes each zone's POSIX footer (the last line of its TZif
/// file). Canonical zones and `backward` links are both included, since
/// phones sometimes report legacy names. Fails if any rule is one the
/// firmware would reject for its length or a `Jn`/`n` day form (ADR-0003).
///
/// Run from `pico_w_display_app/`: `dart run tool/gen_tz_table.dart 2026e`
library;

import 'dart:io';

/// The firmware's `tz::MAX_TZ_LEN`.
const _maxTzLen = 48;

/// The tzdata source files holding zones and links; `factory` is left out.
const _sources = [
  'africa',
  'antarctica',
  'asia',
  'australasia',
  'europe',
  'northamerica',
  'southamerica',
  'etcetera',
  'backward',
];

/// Compiled names that aren't zones a phone would report.
const _skipped = {'Factory', 'posixrules', 'localtime'};

Future<void> main(List<String> args) async {
  if (args.length != 1 || !RegExp(r'^\d{4}[a-z]$').hasMatch(args.single)) {
    stderr.writeln('usage: dart run tool/gen_tz_table.dart <tzdata version>');
    exit(64);
  }
  final version = args.single;
  final work = await Directory.systemTemp.createTemp('tzdata');
  try {
    final rules = await _compile(version, work);
    final problems = [
      for (final MapEntry(key: zone, value: rule) in rules.entries)
        if (_problem(rule) case final problem?) '$zone: "$rule" $problem',
    ];
    if (problems.isNotEmpty) {
      stderr.writeln('tzdata $version has rules the firmware rejects:');
      problems.forEach(stderr.writeln);
      exit(1);
    }
    File('lib/tz/posix_table.g.dart').writeAsStringSync(_dart(version, rules));
    File(
      '../pico_w_display/testdata/tz_rules.txt',
    ).writeAsStringSync(_fixture(version, rules));
    stdout.writeln(
      'tzdata $version: ${rules.length} zones, '
      '${rules.values.toSet().length} distinct rules',
    );
  } finally {
    work.deleteSync(recursive: true);
  }
}

/// Every zone name tzdata [version] defines, to its POSIX footer.
Future<Map<String, String>> _compile(String version, Directory work) async {
  final archive = '${work.path}/tzdata.tar.gz';
  final out = '${work.path}/zoneinfo';
  await _run('curl', [
    '-fsSL',
    'https://data.iana.org/time-zones/releases/tzdata$version.tar.gz',
    '-o',
    archive,
  ]);
  await _run('tar', ['-xzf', archive, '-C', work.path]);
  // Slim TZif: just the footer for the future, which is all that's read.
  await _run('zic', ['-b', 'slim', '-d', out, ..._sources], cwd: work.path);

  final rules = <String, String>{};
  for (final entity in Directory(out).listSync(recursive: true)) {
    if (entity is Directory) continue;
    final zone = entity.path.substring(out.length + 1);
    if (_skipped.contains(zone)) continue;
    rules[zone] = _footer(File(entity.path).readAsBytesSync(), zone);
  }
  return Map.fromEntries(
    rules.entries.toList()..sort((a, b) => a.key.compareTo(b.key)),
  );
}

/// The POSIX TZ string a TZif v2+ file ends with, between two newlines.
String _footer(List<int> tzif, String zone) {
  if (String.fromCharCodes(tzif.take(4)) != 'TZif' || tzif.last != 0x0a) {
    throw FormatException('$zone: not a TZif file with a footer');
  }
  final start = tzif.lastIndexOf(0x0a, tzif.length - 2) + 1;
  final footer = String.fromCharCodes(tzif.sublist(start, tzif.length - 1));
  if (footer.isEmpty) throw FormatException('$zone: empty POSIX footer');
  return footer;
}

/// Why the firmware would reject [rule], or `null` if it wouldn't.
String? _problem(String rule) {
  if (rule.length > _maxTzLen) return 'is over $_maxTzLen bytes';
  // Each transition follows a comma, and must be the `Mm.w.d` form.
  if (rule.split(',').skip(1).any((t) => !t.startsWith('M'))) {
    return 'uses a Jn/n day form';
  }
  return null;
}

String _dart(String version, Map<String, String> rules) {
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_tz_table.dart from tzdata $version.')
    ..writeln('// Do not edit; re-run the tool instead (see README.md).')
    ..writeln()
    ..writeln('/// The tzdata release [posixRules] was generated from.')
    ..writeln("const tzdataVersion = '$version';")
    ..writeln()
    ..writeln('/// IANA zone name (canonical or `backward` link) → POSIX TZ')
    ..writeln('/// Rule, as the tz database itself gives it.')
    ..writeln('const posixRules = <String, String>{');
  for (final MapEntry(key: zone, value: rule) in rules.entries) {
    out.writeln("  '$zone': r'$rule',");
  }
  out.writeln('};');
  return '$out';
}

String _fixture(String version, Map<String, String> rules) {
  final out = StringBuffer()
    ..writeln(
      '# Every distinct POSIX TZ Rule in tzdata $version, one per line.',
    )
    ..writeln(
      '# GENERATED by pico_w_display_app/tool/gen_tz_table.dart; do not edit.',
    );
  for (final rule in rules.values.toSet().toList()..sort()) {
    out.writeln(rule);
  }
  return '$out';
}

Future<void> _run(String exe, List<String> args, {String? cwd}) async {
  final result = await Process.run(exe, args, workingDirectory: cwd);
  if (result.exitCode != 0) {
    stderr
      ..writeln('$exe failed (${result.exitCode}):')
      ..write(result.stderr);
    exit(1);
  }
}
